### ISSUE TITLE
TypeError: must pass in a file:// URI to convert to a file path

### ISSUE THREAD

**Issue by arggh** [ArdenIvanov/svelte-intellisense#21]
My VS Code output console is filled with these:

```
TypeError: must pass in a file:// URI to convert to a file path
    at Object.fileUriToPath (/Users/arggh/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/utils.js:25:15)
    at /Users/arggh/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:63:70
    at CallbackList.invoke (/Users/arggh/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/arggh/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at connection.onDidCloseTextDocument (/Users/arggh/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-languageserver/lib/main.js:202:34)
    at handleNotification (/Users/arggh/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/Users/arggh/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.setImmediate (/Users/arggh/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
```

**Comment by ignatiusmb** [comment]
It's triggered when hovered on the diff page (working tree) in any svelte files. The console output from the dev console is as below
```
ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (c:\Users\Bagus\.vscode\extensions\ardenivanov.svelte-intellisense-0.7.1\client\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (c:\Users\Bagus\.vscode\extensions\ardenivanov.svelte-intellisense-0.7.1\client\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
```
So it seems there's a conflict with the `vscode-languageclient` package in the client folder.

**Comment by himynameisdave** [comment]
+1 

I can help provide debug info if needed!

**Comment by BlackFenix2** [comment]
Having the same exact issue on my end, has any progress been made?

**Comment by ignatiusmb** [comment]
It's been 9 months since the last update, and the Svelte team has built its own [official extension](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) since then, and already out off beta around a month ago.

Probably the solution is to just move to the official extension as they're actively developing it in https://github.com/sveltejs/language-tools/

**Comment by applemate** [comment]
is this fixed yet ? I'm having it . I'm using the latest version of everything as of right now

**Comment by ogrotten** [comment]
Use this instead https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode
