### ISSUE TITLE
Request textDocument/completion failed with message: Cannot read property 'slots' of undefined

### ISSUE THREAD

**Issue by CherryDT** [ArdenIvanov/svelte-intellisense#32]
While developing Svelte files, every few minutes VSCode switches to the "output" tab with "Svelte IntelliSense Language Server" selected in the dropdown (which is annoying since I want the console tab to be visible most of the time), and I see several messages as follows:

```
[Error - 10:06:09 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'slots' of undefined
  Code: -32603 
[Error - 10:06:13 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'slots' of undefined
  Code: -32603 
[Error - 10:08:29 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'slots' of undefined
  Code: -32603 
[Error - 10:08:30 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'slots' of undefined
  Code: -32603 
[Error - 10:11:46 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'slots' of undefined
  Code: -32603 
[Error - 10:11:47 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'slots' of undefined
  Code: -32603 
[Error - 10:11:50 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'slots' of undefined
  Code: -32603 
```

![screen recording](http://g.recordit.co/bO7S8Dp07K.gif)

The same thing happens with `hover` (`Request textDocument/hover failed`) when hovering over attributes of elements which are named slots in some components.

I added logging to your server and got a stack trace:

```
TypeError: Cannot read property 'slots' of undefined
    at NamedSlotParamsService.getNamedSlotDocumentation (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/services/markup/NamedSlotParamsService.js:84:36)
    at NamedSlotParamsService.getHover (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/services/markup/NamedSlotParamsService.js:60:28)
    at /home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/services/ChoosingService.js:29:86
    at /home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/services/ChoosingService.js:50:33
    at Array.some (<anonymous>)
    at TagInnerService.ChoosingService.findServiceResults (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/services/ChoosingService.js:46:24)
    at TagInnerService.ChoosingService.getHover (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/services/ChoosingService.js:29:21)
    at /home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/services/ChoosingService.js:29:86
    at /home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/services/ChoosingService.js:50:33
    at Array.some (<anonymous>)
```

It seems `getNamedSlotDocumentation` is called with a `component` that doesn't have a `sveltedoc`.

`component` is the following thing:
```
SvelteDocument {
  path: '/mnt/c/Users/david/proj/***/src/components/ResourceView.svelte',
  importedComponents: [],
  importResolver: null,
  document: FullTextDocument {
    _uri: 'file:///mnt/c/Users/david/proj/***/src/components/ResourceView.svelte',
    _languageId: 'svelte',
    _version: 0,
    _content: '<script>\n' +
      ' *** CODE HERE *** \n' +
      '</script>\n',
    _lineOffsets: null
  }
}
```

This is from the `hover` case and not the `complete` case, but I guess the root cause will be the same...

By the way, this is in a workspace with multiple projects. Just mentioning because this already caused an issue in another extension which expected that there would be only one ESLint linter instance in the require cache...

I also checked if https://github.com/ArdenIvanov/svelte-intellisense/pull/30 resolves it, but it does not.

**Comment by riez** [comment]
I also have similar issue...

```
[Error - 5:58:03 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 6:02:16 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 6:02:18 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 
[Error - 6:02:19 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 
```

I think on my end the causes is this:
![109488823-a540f180-7ab8-11eb-84b3-97304d00328b](https://user-images.githubusercontent.com/37952353/109489059-ecc77d80-7ab8-11eb-8810-45fbc20373a8.gif)

**Comment by CherryDT** [comment]
This happens also sometimes with `textDocument/hover`, yes, for me too, but for me it's also `slots` and not `data` which is being read then.

**Comment by CherryDT** [comment]
I put a $30 bounty on this issue now: https://www.bountysource.com/issues/97052110-request-textdocument-completion-failed-with-message-cannot-read-property-slots-of-undefined

**Comment by alexprey** [comment]
@CherryDT do you have examples of files where this issue appears?

**Comment by CherryDT** [comment]
The problem is, if I isolate a file where it happens, it no longer happens. Seems the "surroundings" play a part in this. (And I can't share the actual project.) Is there some way to add more verbose logging so that I can help you diagnose the problem nonetheless?

**Comment by CherryDT** [comment]
This file for example causes it for me, for example when hovering over one of the `<div>` tags:

```html
<script>
  export let topView
  export let closeSelf
  export let closeHigher
  export let openAndReplace

  export let id
  export let title
  export let onSave

  import ResourceView from '../components/ResourceView.svelte'
  import { apiCall } from '../lib/api'
  import ViewCustomerForm from './ViewCustomerForm.svelte'
  import ViewPropertyDetails from './ViewPropertyDetails.svelte'
  import ViewPropertyForm from './ViewPropertyForm.svelte'
  import Detail from '../components/Detail.svelte'

  let username
</script>

<ResourceView
  {topView} {closeSelf} {closeHigher} {openAndReplace}
  {id} {title}
  defaultTitle="Kundendetails"
  {onSave}
  getTitle={record => `${record.company} (#${record.customerNo})`}
  getChildTitle={record => record.name}
  order="name"
  select="name,address,interval"
  filter={JSON.stringify({ customer: id })}
  icon="building"
  handleLoad={async (id, mainRecord, items, keepViews) => {
    const [user] = await apiCall('GET', '/users', { filter: JSON.stringify({ customer: id }), select: 'username' })
    username = user?.username
  }}
  resourcePath="/customers"
  resourceName="Kunde"
  childResourcePath="/properties"
  childResourceName="Liegenschaft"
  childResourceGender="f"
  ViewMainForm={ViewCustomerForm}
  ViewChildDetails={ViewPropertyDetails}
  ViewChildForm={ViewPropertyForm}
  search={(searchQuery, searchRegex, record) => record.name?.match(searchRegex) || record.address?.match(searchRegex)}
  allowEdit={true}
  allowDelete={true}
  canDelete={(mainRecord, items) => !items.length}
  let:record
>
  <div slot="header" class="panel-block" let:mainRecord>
    <Detail title="Anschrift" icon="envelope" ready={mainRecord?.address}>
      {mainRecord?.address?.split('\n').join('; ')}
    </Detail>
  </div>

  <div slot="header" class="panel-block" let:mainRecord class:is-hidden={!username}>
    <Detail title="Benutzername" icon="user">
      {username}
    </Detail>
  </div>

  <div slot="header" class="panel-block" let:mainRecord class:is-hidden={!mainRecord?.notes}>
    <Detail title="Notizen" icon="sticky-note" ready={mainRecord?.notes}>
      {mainRecord?.notes?.split('\n').join('; ')}
    </Detail>
  </div>

  <span class="list-entry" class:is-disabled={!record.interval}>{record.name}<br /><small>{record.address.split('\n').join('; ')}</small></span>
</ResourceView>
```

Note: the same thing happens after refactoring this to the new Svelte 3.35.0 way (it shows up when hovering over the `<svelte:fragment>` then, so it's not the duplicate slots causing this:

```html
<script>
  export let topView
  export let closeSelf
  export let closeHigher
  export let openAndReplace

  export let id
  export let title
  export let onSave

  import ResourceView from '../components/ResourceView.svelte'
  import { apiCall } from '../lib/api'
  import ViewCustomerForm from './ViewCustomerForm.svelte'
  import ViewPropertyDetails from './ViewPropertyDetails.svelte'
  import ViewPropertyForm from './ViewPropertyForm.svelte'
  import Detail from '../components/Detail.svelte'

  let username
</script>

<ResourceView
  {topView} {closeSelf} {closeHigher} {openAndReplace}
  {id} {title}
  defaultTitle="Kundendetails"
  {onSave}
  getTitle={record => `${record.company} (#${record.customerNo})`}
  getChildTitle={record => record.name}
  order="name"
  select="name,address,interval"
  filter={JSON.stringify({ customer: id })}
  icon="building"
  handleLoad={async (id, mainRecord, items, keepViews) => {
    const [user] = await apiCall('GET', '/users', { filter: JSON.stringify({ customer: id }), select: 'username' })
    username = user?.username
  }}
  resourcePath="/customers"
  resourceName="Kunde"
  childResourcePath="/properties"
  childResourceName="Liegenschaft"
  childResourceGender="f"
  ViewMainForm={ViewCustomerForm}
  ViewChildDetails={ViewPropertyDetails}
  ViewChildForm={ViewPropertyForm}
  search={(searchQuery, searchRegex, record) => record.name?.match(searchRegex) || record.address?.match(searchRegex)}
  allowEdit={true}
  allowDelete={true}
  canDelete={(mainRecord, items) => !items.length}
  let:record
>
  <svelte:fragment slot="header" let:mainRecord>
    <div class="panel-block">
      <Detail title="Anschrift" icon="envelope" ready={mainRecord?.address}>
        {mainRecord?.address?.split('\n').join('; ')}
      </Detail>
    </div>

    <div class="panel-block" class:is-hidden={!username}>
      <Detail title="Benutzername" icon="user">
        {username}
      </Detail>
    </div>

    <div class="panel-block" class:is-hidden={!mainRecord?.notes}>
      <Detail title="Notizen" icon="sticky-note" ready={mainRecord?.notes}>
        {mainRecord?.notes?.split('\n').join('; ')}
      </Detail>
    </div>
  </svelte:fragment>

  <span class="list-entry" class:is-disabled={!record.interval}>{record.name}<br /><small>{record.address.split('\n').join('; ')}</small></span>
</ResourceView>
```

**Comment by CherryDT** [comment]
Added a stack trace to my initial post

**Comment by CherryDT** [comment]
Are there any updates about this? This is annoying me for over a year now 😭 because it keeps switching my panel to the output tab...

Not always the same errors, all kinds of errors in fact, but still the same effect.

Right now it's for example this:

```
[Error - 2:57:45 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: EISDIR: illegal operation on a directory, read
  Code: -32603 
```

...or this:

```
TypeError: must pass in a file:// URI to convert to a file path
    at Object.fileUriToPath (/home/david/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/utils.js:25:15)
    at reloadDocument (/home/david/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:69:70)
    at /home/david/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:60:5
    at CallbackList.invoke (/home/david/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/david/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at /home/david/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-languageserver/lib/main.js:181:38
    at handleNotification (/home/david/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/home/david/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate._onImmediate (/home/david/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (node:internal/timers:464:21)
```

...every few lines of editing this happens. Hundreds of times per day. It's infuriating. _Please_ help me... It would already be enough if you would prevent the tab-switching! I don't care if there are errors accumulating in some tab I am not looking at, but it's a problem when it shoves them into my face every few seconds.

(And remember there is a $30 bounty on BountySource for fixing this...)

**Comment by DanChristos** [comment]
I was having the same issue, but for me I was able to narrow it down specifically to a component that I had installed via npm called svelte-datepickr. The component itself is called Flatpickr.svelte. When I moved the component from the node_modules and into my project's src directory the problem went away. I don't really know why though. From what I can understand this kind of error can come up for a variety of reasons, so I'm not sure that my case will be able to help you with yours or not. I hope you get to the bottom of it.

**Comment by CherryDT** [comment]
In my case I feel it's related to `svelma` but it also spmetom sometimes happens with my own components

**Comment by DanChristos** [comment]
Ok I've had a deeper look into my case and figured out that the error shows up when I import as such: `import Flatpickr from 'svelte-flatpickr'` but if I reference the file directly with `import Flatpickr from 'svelte-flatpickr/src/Flatpickr.svelte'` the error no longer shows up. I think it might have something to do with vscode (or svelte intellisense) using the .ts file for loading the hover information.

**Comment by DanChristos** [comment]
This one works better, doesn't have any errors show up https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

**Comment by DanChristos** [comment]
Ok I disabled svelte-intellisense and installed [Svelte for VS Code](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) instead. It's built by the svelte guys. No error.
