### ISSUE TITLE
TypeError: must pass in a file:// URI to convert to a file path

### ISSUE THREAD

**Issue by CherryDT** [ArdenIvanov/svelte-intellisense#34]
I'm getting this error in the output panel when opening a new file (without saving it yet) and pasting in Svelte code:

```
TypeError: must pass in a file:// URI to convert to a file path
    at Object.fileUriToPath (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/utils.js:25:15)
    at reloadDocument (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:69:70)
    at /home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:60:5
    at CallbackList.invoke (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at /home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-languageserver/lib/main.js:181:38
    at handleNotification (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate._onImmediate (/home/david/.vscode-server-insiders/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:456:21)
```

**Comment by ejolly** [comment]
I'm also getting a similar error if I hover over any code diffs on svelte files:

```
[Error - 7:14:06 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603
```

**Comment by RhettA** [comment]
I'm having this still on Jun 12 with everything updated. It's quite irritating because it makes the output window pop up over and over.

**Comment by kyle-barth** [comment]
Same experience here was wondering if anyone else had a solution.

**Comment by RhettA** [comment]
> Same experience here was wondering if anyone else had a solution.

I think we're supposed to stop using this and rely on the "Svelte for VS Code" extension.

**Comment by MaMrEzO** [comment]
I have this error just in Source control file viewer, this is not happens anywhere else!

**Comment by enBonnet** [comment]
Same error

**Comment by enBonnet** [comment]
Duplicated https://github.com/ArdenIvanov/svelte-intellisense/issues/21

**Comment by ogrotten** [comment]
You should use this instead https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode
