### ISSUE TITLE
Return of "Request textDocument/hover failed"

### ISSUE THREAD

**Issue by ogrotten** [ArdenIvanov/svelte-intellisense#44]
Reference: #14 

---

This started happening to me somewhere about a week ago (mid Oct, 2021). I have no idea what started it, but I looked over to the `Terminal` and instead it was curiously on `Output`. Yesterday it happened again, was incessant for "a while" and then just stopped. Since I was thinking about the content of the code, I wasn't paying attention to what started/stopped it.

Today, I used GitLens to open a compare view of a past commit of a file, and `Output` panel popped and started spamming. 

I would post a video, but privacy. So to reproduce:

1. open a file in a project 
1. have GitLens installed
1. go to VSCode Source Control 
1. open File History panel
1. click original commit of the file
1. hover **_anything_** green in the file.

I know it initially looks like it could be a GitLens problem, but I use this _only_ because I know that it's a path for reliable reproduction. I don't use GitLens directly very often, but I happened to see it here and can give the steps to reproduce.

```
TypeError: must pass in a file:// URI to convert to a file path
    at Object.fileUriToPath (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/utils.js:25:15)
    at reloadDocument (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:69:70)
    at /home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:60:5
    at CallbackList.invoke (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at /home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-languageserver/lib/main.js:181:38
    at handleNotification (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate._onImmediate (/home/username/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:461:21)
[Error - 9:53:21 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
[Error - 9:53:37 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
[Error - 9:53:37 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
[Error - 9:54:00 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
[Error - 9:54:02 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
```

The first `TypeError` scrolls up for 16.7km. Without timestamps I can't know how long they've been accumulating.

I have no problem helping directly as I can produce the problem reliably.

**Comment by csellis** [comment]
Any progress on this?

**Comment by antiv** [comment]
Hi I have same problem:

```
TypeError: must pass in a file:// URI to convert to a file path
    at Object.fileUriToPath (/home/ivan/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/utils.js:25:15)
    at reloadDocument (/home/ivan/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:69:70)
    at /home/ivan/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:60:5
    at CallbackList.invoke (/home/ivan/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/ivan/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at /home/ivan/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-languageserver/lib/main.js:181:38
    at handleNotification (/home/ivan/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/home/ivan/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate._onImmediate (/home/ivan/.vscode/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:461:21)

```
and also 
```
[Error - 7:42:18 AM] Request textDocument/hover failed.
 Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
```

the problem started to appear a few days ago

**Comment by ogrotten** [comment]
Here's some additional info. I had a much more specific moment today and I caught it as it happened.

![image](https://user-images.githubusercontent.com/8119012/145895192-2c426dfb-f409-43af-adc7-5f07437dbd97.png)

On hover, the highlighted `bind` produces this error:
```
[Error - 3:54:11 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 
```

I highlighted the first one, then used `ctrl-d` to select the others. As I was moving my mouse to do something else, it passed over one of the highlights and the Output panel popped. It doesn't seem to do it on the first hover, only on the 2nd or later.

Hope this helps.

[edit] now it seems that it won't stop. It also managed to kick out an additional message one single time:
```
[Error - 4:04:36 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'events' of undefined
  Code: -32603 
```

**Comment by ogrotten** [comment]
Use https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode
