### ISSUE TITLE
Output panel keeps popping up

### ISSUE THREAD

**Issue by jmbeach** [ArdenIvanov/svelte-intellisense#56]
The output panel keeps popping up in the middle of typing because it runs into an error such as "Request textDocument/hover" failed. I'd really like it to stay hidden.

Seems very similar to this issue https://github.com/jamesbirtles/svelte-vscode/issues/41

**Comment by MrVauxs** [comment]
It's really annoying when even hovering for a second a `svelte-fa` element.
```
[Error - 6:00:36 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: EISDIR: illegal operation on a directory, read
  Code: -32603 
  ```

**Comment by paolodina** [comment]
```
[Error - 11:05:01 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 
```

**Comment by dromzeh** [comment]
Also getting this issue where it completely floods the panel.

```
TypeError: must pass in a file:// URI to convert to a file path
    at Object.fileUriToPath (c:\Users\marcel\.vscode-insiders\extensions\ardenivanov.svelte-intellisense-0.7.1\server\out\utils.js:25:15)
    at reloadDocument (c:\Users\marcel\.vscode-insiders\extensions\ardenivanov.svelte-intellisense-0.7.1\server\out\server.js:69:70)
```

**Comment by kate-jiang** [comment]
Any update here?

**Comment by Carlos-err406** [comment]
also getting this, so frustrating
sad that it seems like is not going to be fixed

**Comment by dromzeh** [comment]
> sad that it seems like is not going to be fixed

Seems the maintainer is no longer active looking at his contribution graph; making a fix PR directly to this repo seems to be practically useless - unless someone ends up forking && maintaining this... I'll see if I can get a fix out to my fork if I have some spare time.

**Comment by reecelikesramen** [comment]
This issue also seems related to #44, #34, and #32. I'm experiencing a similar issue, the output panel comes up each time I open the git blame for a .svelte file I'm staging.

**Comment by marlopainter** [comment]
This is still happening, and bothering me.
After reading here, I looked into other options.
Adding this to the settings.json is the best solution for me, so far. 
The Output still logs, but doesn't make itself visible.
Your own mileage may vary.

```
	"workbench.view.showQuietly": {
		"workbench.panel.output": true
	}
```

**Comment by sf1tzp** [comment]
This also occurs with svelte code previews in the copilot chat sidebar. Thanks for the tip @marlopainter

**Comment by adamdva** [comment]
This is very annoying, here's the full error I see:
`TypeError: must pass in a file:// URI to convert to a file path
    at Object.fileUriToPath (/home/codespace/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/utils.js:25:15)
    at reloadDocument (/home/codespace/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:69:70)
    at /home/codespace/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/out/server.js:60:5
    at CallbackList.invoke (/home/codespace/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/codespace/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at /home/codespace/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-languageserver/lib/main.js:194:46
    at handleNotification (/home/codespace/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/home/codespace/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate._onImmediate (/home/codespace/.vscode-server/extensions/ardenivanov.svelte-intellisense-0.7.1/server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at process.processImmediate (node:internal/timers:483:21)
[Error - 12:21:22 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: must pass in a file:// URI to convert to a file path
  Code: -32603 `

**Comment by justingolden21** [comment]
Noticing this as well and it only started recently. The last commit here is **6 years ago**, which to me means 2 things: 1) the extension isn't being maintained, and 2) this bug isn't necessarily entirely due to the extension, so something else in VS code messed this up, since it worked fine for years and hasn't been updated.

**Comment by ogrotten** [comment]
Use this instead https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode
